### ISSUE TITLE
画面の横幅について

### ISSUE THREAD

**Issue by SeiyaMogami** [InoueDaiki/learning-tools#3]
# 問題
ログイン画面の横幅がスマホ画面に収まっておらず、画面が横に動いてしまいます。

# 原因
おそらく、div.columnに不要なPaddingが設定されているためです。スマホサイズではW:375pxになることがほとんどなのですが、該当部分はW:403pxとなっています。

**Comment by InoueDaiki** [comment]
ご指摘ありがとうございます。
containerを忘れていました...

**Comment by SeiyaMogami** [comment]
LGTM
